name: Go CI Pipeline

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: true
    
    - name: Install dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Run golangci-lint
      id: lint
      uses: golangci/golangci-lint-action@v3
      continue-on-error: true
      with:
        version: latest

    - name: Process lint results
      if: always()
      run: |
        echo "Lint status: ${{ steps.lint.outcome }}"

    - name: Run Tests
      run: go test -v ./...
      env:
        DB_HOST: localhost
        DB_NAME: pubplay

    - name: Build
      run: go build -v ./...

    - name: Build Docker image
      run: docker build -t publist-backend .